### PR TITLE
Update README.md for New Users

### PR DESCRIPTION
**Pull request by AlecNesatColak**
Updates made in the README.md file for user guidelines and steps for setting up the repository locally as well as how to properly make contributions and code changes. The new README includes instructions on prerequisites, installation, and setup to get the project running locally. It offers an overview of the app's architecture, highlighting the main components and their roles. The goal of this README is to provide clear and concise information to help new developers understand the project structure and get started quickly, while also serving as a reference for existing contributors.

### CODE REVIEW

**Comment by sosauce** [comment]
Hello ! This is uhm, interesting ? I's think anybody wanting to contribute to a project would know how to 😅 Do you know other projects with these instructions in their readme ?

**Comment by AlecNesatColak** [comment]
Thanks for the quick reply. Every project I have been a part of or contributed, including professional work projects have had some sort of at least "set-up" guide or a run script/docker startup instructions. I do see how it can be seen as trivial, but maybe not for those new to the project especially

**Comment by sosauce** [comment]
I see then, I'll probably have a get started readme if thats 'do-able' so the main readme is just about the app, since this is an app more than a tool for people to build and use, I'll see tomorrow it's late here !

**Comment by AlecNesatColak** [comment]
That sounds good, it may well be a preference thing too, some projects will have those guidelines within their specific directories that those instructions take place within or as you said, a "get started". Either way sounds good!

**Pull request merged**
